### ISSUE TITLE
SASS 中的 @extend、@mixin 与重复的 css 片段

### ISSUE THREAD

**Issue by lmk123** [lmk123/blog#17]
最近在新项目中使用了 [SASS](http://sass-lang.com/)，不得不说，用了它之后，写 css 变得有趣了。

但今天在无意中发现了一个小问题：生成的 css 文件中有很多重复的片段。

举例来说：
```scss
@mixin common {
    color:red;
}

.error {
    @include common;
    font-size:14px;
}

.big-error {
    @include common;
    font-size:24px;
}
```
因为这两个类用到了同一个片段，所以我想像中应该生成的 css 文件是这样的：
```css
.error,.big-error{ /* 共用相同的片段 */
    color:red;
}

.error {
    font-size:14px;
}

.big-error {
    font-size:24px;
}
```
但结果它生成的是这样：
```css
.error {
    color:red; /* 单独插入，没有共用 */
    font-size:14px;
}

.big-error {
    color:red;
    font-size:24px;
}
```
这时我才发现，[@mixin](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixins)并不会像[@extend](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#extend)那样公用 css 片段。

那为什么我没有用`@extend`呢？我一开始确实用到了，是这样写的：
```scss
.error {
    color:red;
}

.small-error {
    @extend .error;
    font-size:14px;
}

.big-error {
    @extend .error;
    font-size:24px;
}
```
但这样写有一个问题：css 文件里面会生成一个 `.error` ——一个只是被用来 extend 的、并不会在 html 中用到的类。

在查阅相关文档后，问题得到了解决：使用 [@extend-Only Selectors](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#placeholders)
